# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE := third_party_libjpeg_turbo_libjpeg_gyp
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_TARGET_ARCH := $(TARGET_$(GYP_VAR_PREFIX)ARCH)
gyp_intermediate_dir := $(call local-intermediates-dir,,$(GYP_VAR_PREFIX))
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared,,,$(GYP_VAR_PREFIX))

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES := \
	$(gyp_shared_intermediate_dir)/yasm


### Generated for rule "third_party_libjpeg_turbo_libjpeg_gyp_libjpeg_target_assemble":
# "{'inputs': ['$(gyp_shared_intermediate_dir)/yasm'], 'process_outputs_as_sources': '1', 'extension': 'asm', 'outputs': ['$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/%(INPUT_ROOT)s.o'], 'rule_name': 'assemble', 'rule_sources': ['simd/jccolmmx.asm', 'simd/jccolss2.asm', 'simd/jcgrammx.asm', 'simd/jcgrass2.asm', 'simd/jcqnt3dn.asm', 'simd/jcqntmmx.asm', 'simd/jcqnts2f.asm', 'simd/jcqnts2i.asm', 'simd/jcqntsse.asm', 'simd/jcsammmx.asm', 'simd/jcsamss2.asm', 'simd/jdcolmmx.asm', 'simd/jdcolss2.asm', 'simd/jdmermmx.asm', 'simd/jdmerss2.asm', 'simd/jdsammmx.asm', 'simd/jdsamss2.asm', 'simd/jf3dnflt.asm', 'simd/jfmmxfst.asm', 'simd/jfmmxint.asm', 'simd/jfss2fst.asm', 'simd/jfss2int.asm', 'simd/jfsseflt.asm', 'simd/ji3dnflt.asm', 'simd/jimmxfst.asm', 'simd/jimmxint.asm', 'simd/jimmxred.asm', 'simd/jiss2flt.asm', 'simd/jiss2fst.asm', 'simd/jiss2int.asm', 'simd/jiss2red.asm', 'simd/jisseflt.asm', 'simd/jsimdcpu.asm'], 'action': ['$(gyp_shared_intermediate_dir)/yasm', '-felf', '-D__x86__', '-DELF', '-Ilinux/', '-DRGBX_FILLER_0XFF', '-DSTRICT_MEMORY_ACCESS', '-Isimd/', '-o', '$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/%(INPUT_ROOT)s.o', '$(RULE_SOURCES)'], 'message': 'Building %(INPUT_ROOT)s.o'}":
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolmmx.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolmmx.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolmmx.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolmmx.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolmmx.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolmmx.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jccolmmx.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolmmx.o" simd/jccolmmx.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolss2.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolss2.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolss2.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolss2.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolss2.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolss2.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jccolss2.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolss2.o" simd/jccolss2.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrammx.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrammx.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrammx.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrammx.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrammx.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrammx.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jcgrammx.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrammx.o" simd/jcgrammx.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrass2.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrass2.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrass2.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrass2.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrass2.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrass2.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jcgrass2.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrass2.o" simd/jcgrass2.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnt3dn.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnt3dn.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnt3dn.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnt3dn.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnt3dn.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnt3dn.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jcqnt3dn.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnt3dn.o" simd/jcqnt3dn.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntmmx.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntmmx.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntmmx.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntmmx.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntmmx.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntmmx.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jcqntmmx.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntmmx.o" simd/jcqntmmx.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2f.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2f.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2f.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2f.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2f.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2f.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jcqnts2f.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2f.o" simd/jcqnts2f.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2i.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2i.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2i.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2i.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2i.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2i.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jcqnts2i.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2i.o" simd/jcqnts2i.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntsse.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntsse.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntsse.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntsse.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntsse.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntsse.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jcqntsse.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntsse.o" simd/jcqntsse.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsammmx.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsammmx.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsammmx.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsammmx.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsammmx.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsammmx.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jcsammmx.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsammmx.o" simd/jcsammmx.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsamss2.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsamss2.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsamss2.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsamss2.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsamss2.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsamss2.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jcsamss2.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsamss2.o" simd/jcsamss2.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolmmx.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolmmx.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolmmx.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolmmx.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolmmx.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolmmx.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jdcolmmx.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolmmx.o" simd/jdcolmmx.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolss2.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolss2.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolss2.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolss2.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolss2.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolss2.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jdcolss2.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolss2.o" simd/jdcolss2.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmermmx.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmermmx.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmermmx.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmermmx.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmermmx.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmermmx.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jdmermmx.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmermmx.o" simd/jdmermmx.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmerss2.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmerss2.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmerss2.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmerss2.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmerss2.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmerss2.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jdmerss2.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmerss2.o" simd/jdmerss2.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsammmx.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsammmx.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsammmx.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsammmx.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsammmx.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsammmx.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jdsammmx.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsammmx.o" simd/jdsammmx.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsamss2.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsamss2.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsamss2.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsamss2.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsamss2.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsamss2.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jdsamss2.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsamss2.o" simd/jdsamss2.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jf3dnflt.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jf3dnflt.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jf3dnflt.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jf3dnflt.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jf3dnflt.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jf3dnflt.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jf3dnflt.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jf3dnflt.o" simd/jf3dnflt.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxfst.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxfst.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxfst.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxfst.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxfst.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxfst.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jfmmxfst.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxfst.o" simd/jfmmxfst.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxint.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxint.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxint.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxint.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxint.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxint.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jfmmxint.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxint.o" simd/jfmmxint.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2fst.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2fst.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2fst.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2fst.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2fst.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2fst.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jfss2fst.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2fst.o" simd/jfss2fst.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2int.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2int.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2int.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2int.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2int.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2int.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jfss2int.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2int.o" simd/jfss2int.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfsseflt.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfsseflt.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfsseflt.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfsseflt.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfsseflt.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfsseflt.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jfsseflt.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfsseflt.o" simd/jfsseflt.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/ji3dnflt.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/ji3dnflt.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/ji3dnflt.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/ji3dnflt.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/ji3dnflt.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/ji3dnflt.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/ji3dnflt.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/ji3dnflt.o" simd/ji3dnflt.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxfst.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxfst.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxfst.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxfst.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxfst.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxfst.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jimmxfst.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxfst.o" simd/jimmxfst.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxint.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxint.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxint.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxint.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxint.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxint.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jimmxint.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxint.o" simd/jimmxint.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxred.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxred.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxred.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxred.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxred.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxred.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jimmxred.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxred.o" simd/jimmxred.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2flt.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2flt.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2flt.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2flt.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2flt.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2flt.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jiss2flt.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2flt.o" simd/jiss2flt.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2fst.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2fst.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2fst.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2fst.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2fst.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2fst.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jiss2fst.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2fst.o" simd/jiss2fst.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2int.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2int.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2int.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2int.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2int.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2int.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jiss2int.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2int.o" simd/jiss2int.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2red.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2red.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2red.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2red.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2red.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2red.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jiss2red.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2red.o" simd/jiss2red.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jisseflt.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jisseflt.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jisseflt.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jisseflt.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jisseflt.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jisseflt.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jisseflt.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jisseflt.o" simd/jisseflt.asm


$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jsimdcpu.o: gyp_local_path := $(LOCAL_PATH)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jsimdcpu.o: gyp_var_prefix := $(GYP_VAR_PREFIX)
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jsimdcpu.o: gyp_intermediate_dir := $(abspath $(gyp_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jsimdcpu.o: gyp_shared_intermediate_dir := $(abspath $(gyp_shared_intermediate_dir))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jsimdcpu.o: export PATH := $(subst $(ANDROID_BUILD_PATHS),,$(PATH))
$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jsimdcpu.o: $(LOCAL_PATH)/third_party/libjpeg_turbo/simd/jsimdcpu.asm $(gyp_shared_intermediate_dir)/yasm $(GYP_TARGET_DEPENDENCIES)
	mkdir -p $(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo; cd $(gyp_local_path)/third_party/libjpeg_turbo; "$(gyp_shared_intermediate_dir)/yasm" -felf -D__x86__ -DELF -Ilinux/ -DRGBX_FILLER_0XFF -DSTRICT_MEMORY_ACCESS -Isimd/ -o "$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jsimdcpu.o" simd/jsimdcpu.asm



GYP_GENERATED_OUTPUTS := \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolmmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolss2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrammx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrass2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnt3dn.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntmmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2f.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2i.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntsse.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsammmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsamss2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolmmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolss2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmermmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmerss2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsammmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsamss2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jf3dnflt.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxfst.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxint.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2fst.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2int.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfsseflt.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/ji3dnflt.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxfst.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxint.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxred.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2flt.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2fst.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2int.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2red.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jisseflt.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jsimdcpu.o

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

LOCAL_GENERATED_SOURCES := \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolmmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jccolss2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrammx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcgrass2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnt3dn.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntmmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2f.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqnts2i.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcqntsse.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsammmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jcsamss2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolmmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdcolss2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmermmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdmerss2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsammmx.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jdsamss2.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jf3dnflt.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxfst.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfmmxint.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2fst.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfss2int.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jfsseflt.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/ji3dnflt.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxfst.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxint.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jimmxred.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2flt.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2fst.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2int.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jiss2red.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jisseflt.o \
	$(gyp_shared_intermediate_dir)/third_party/libjpeg_turbo/jsimdcpu.o

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	third_party/libjpeg_turbo/jcapimin.c \
	third_party/libjpeg_turbo/jcapistd.c \
	third_party/libjpeg_turbo/jccoefct.c \
	third_party/libjpeg_turbo/jccolor.c \
	third_party/libjpeg_turbo/jcdctmgr.c \
	third_party/libjpeg_turbo/jchuff.c \
	third_party/libjpeg_turbo/jcinit.c \
	third_party/libjpeg_turbo/jcmainct.c \
	third_party/libjpeg_turbo/jcmarker.c \
	third_party/libjpeg_turbo/jcmaster.c \
	third_party/libjpeg_turbo/jcomapi.c \
	third_party/libjpeg_turbo/jcparam.c \
	third_party/libjpeg_turbo/jcphuff.c \
	third_party/libjpeg_turbo/jcprepct.c \
	third_party/libjpeg_turbo/jcsample.c \
	third_party/libjpeg_turbo/jdapimin.c \
	third_party/libjpeg_turbo/jdapistd.c \
	third_party/libjpeg_turbo/jdatadst.c \
	third_party/libjpeg_turbo/jdatasrc.c \
	third_party/libjpeg_turbo/jdcoefct.c \
	third_party/libjpeg_turbo/jdcolor.c \
	third_party/libjpeg_turbo/jddctmgr.c \
	third_party/libjpeg_turbo/jdhuff.c \
	third_party/libjpeg_turbo/jdinput.c \
	third_party/libjpeg_turbo/jdmainct.c \
	third_party/libjpeg_turbo/jdmarker.c \
	third_party/libjpeg_turbo/jdmaster.c \
	third_party/libjpeg_turbo/jdmerge.c \
	third_party/libjpeg_turbo/jdphuff.c \
	third_party/libjpeg_turbo/jdpostct.c \
	third_party/libjpeg_turbo/jdsample.c \
	third_party/libjpeg_turbo/jerror.c \
	third_party/libjpeg_turbo/jfdctflt.c \
	third_party/libjpeg_turbo/jfdctfst.c \
	third_party/libjpeg_turbo/jfdctint.c \
	third_party/libjpeg_turbo/jidctflt.c \
	third_party/libjpeg_turbo/jidctfst.c \
	third_party/libjpeg_turbo/jidctint.c \
	third_party/libjpeg_turbo/jidctred.c \
	third_party/libjpeg_turbo/jmemmgr.c \
	third_party/libjpeg_turbo/jmemnobs.c \
	third_party/libjpeg_turbo/jquant1.c \
	third_party/libjpeg_turbo/jquant2.c \
	third_party/libjpeg_turbo/jutils.c \
	third_party/libjpeg_turbo/simd/jsimd_i386.c


# Flags passed to both C and C++ files.
MY_CFLAGS_Debug := \
	--param=ssp-buffer-size=4 \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-unused-local-typedefs \
	-Wno-format \
	-msse2 \
	-mfpmath=sse \
	-mmmx \
	-m32 \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	-U_FORTIFY_SOURCE \
	-Wno-extra \
	-Wno-ignored-qualifiers \
	-Wno-type-limits \
	-Wno-unused-but-set-variable \
	-fno-stack-protector \
	-Wno-address \
	-Wno-format-security \
	-Wno-return-type \
	-Wno-sequence-point \
	-Os \
	-g \
	-gdwarf-4 \
	-fdata-sections \
	-ffunction-sections \
	-fomit-frame-pointer \
	-funwind-tables

MY_DEFS_Debug := \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DENABLE_WEBRTC=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_BROWSER_CDMS' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DDISCARDABLE_MEMORY_ALWAYS_SUPPORTED_NATIVELY' \
	'-DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE' \
	'-DENABLE_EGLIMAGE=1' \
	'-DCLD_VERSION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DDATA_REDUCTION_FALLBACK_HOST="http://compress.googlezip.net:80/"' \
	'-DDATA_REDUCTION_DEV_HOST="https://proxy-dev.googlezip.net:443/"' \
	'-DDATA_REDUCTION_DEV_FALLBACK_HOST="http://proxy-dev.googlezip.net:80/"' \
	'-DSPDY_PROXY_AUTH_ORIGIN="https://proxy.googlezip.net:443/"' \
	'-DDATA_REDUCTION_PROXY_PROBE_URL="http://check.googlezip.net/connect"' \
	'-DDATA_REDUCTION_PROXY_WARMUP_URL="http://www.gstatic.com/generate_204"' \
	'-DVIDEO_HOLE=1' \
	'-DENABLE_LOAD_COMPLETION_HACKS=1' \
	'-DWITH_SIMD' \
	'-DMOTION_JPEG_SUPPORTED' \
	'-DNO_GETENV' \
	'-DUSE_OPENSSL=1' \
	'-DUSE_OPENSSL_CERTS=1' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_BUILD_ID=""' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=1' \
	'-DWTF_USE_DYNAMIC_ANNOTATIONS=1' \
	'-D_DEBUG'


# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES_Debug := \
	$(gyp_shared_intermediate_dir) \
	$(LOCAL_PATH)/third_party/libjpeg_turbo \
	$(PWD)/frameworks/wilhelm/include \
	$(PWD)/bionic \
	$(PWD)/external/stlport/stlport


# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS_Debug := \
	-fno-exceptions \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated \
	-std=gnu++11 \
	-Wno-narrowing \
	-Wno-literal-suffix \
	-Wno-non-virtual-dtor \
	-Wno-sign-promo \
	-Wno-non-virtual-dtor


# Flags passed to both C and C++ files.
MY_CFLAGS_Release := \
	--param=ssp-buffer-size=4 \
	-fno-strict-aliasing \
	-Wno-unused-parameter \
	-Wno-missing-field-initializers \
	-fvisibility=hidden \
	-pipe \
	-fPIC \
	-Wno-unused-local-typedefs \
	-Wno-format \
	-msse2 \
	-mfpmath=sse \
	-mmmx \
	-m32 \
	-ffunction-sections \
	-funwind-tables \
	-g \
	-fno-short-enums \
	-finline-limit=64 \
	-Wa,--noexecstack \
	-U_FORTIFY_SOURCE \
	-Wno-extra \
	-Wno-ignored-qualifiers \
	-Wno-type-limits \
	-Wno-unused-but-set-variable \
	-fno-stack-protector \
	-Wno-address \
	-Wno-format-security \
	-Wno-return-type \
	-Wno-sequence-point \
	-Os \
	-fno-ident \
	-fdata-sections \
	-ffunction-sections \
	-fomit-frame-pointer \
	-funwind-tables

MY_DEFS_Release := \
	'-DV8_DEPRECATION_WARNINGS' \
	'-D_FILE_OFFSET_BITS=64' \
	'-DNO_TCMALLOC' \
	'-DDISABLE_NACL' \
	'-DCHROMIUM_BUILD' \
	'-DUSE_LIBJPEG_TURBO=1' \
	'-DENABLE_WEBRTC=1' \
	'-DUSE_PROPRIETARY_CODECS' \
	'-DENABLE_BROWSER_CDMS' \
	'-DENABLE_CONFIGURATION_POLICY' \
	'-DDISCARDABLE_MEMORY_ALWAYS_SUPPORTED_NATIVELY' \
	'-DSYSTEM_NATIVELY_SIGNALS_MEMORY_PRESSURE' \
	'-DENABLE_EGLIMAGE=1' \
	'-DCLD_VERSION=1' \
	'-DENABLE_PRINTING=1' \
	'-DENABLE_MANAGED_USERS=1' \
	'-DDATA_REDUCTION_FALLBACK_HOST="http://compress.googlezip.net:80/"' \
	'-DDATA_REDUCTION_DEV_HOST="https://proxy-dev.googlezip.net:443/"' \
	'-DDATA_REDUCTION_DEV_FALLBACK_HOST="http://proxy-dev.googlezip.net:80/"' \
	'-DSPDY_PROXY_AUTH_ORIGIN="https://proxy.googlezip.net:443/"' \
	'-DDATA_REDUCTION_PROXY_PROBE_URL="http://check.googlezip.net/connect"' \
	'-DDATA_REDUCTION_PROXY_WARMUP_URL="http://www.gstatic.com/generate_204"' \
	'-DVIDEO_HOLE=1' \
	'-DENABLE_LOAD_COMPLETION_HACKS=1' \
	'-DWITH_SIMD' \
	'-DMOTION_JPEG_SUPPORTED' \
	'-DNO_GETENV' \
	'-DUSE_OPENSSL=1' \
	'-DUSE_OPENSSL_CERTS=1' \
	'-DANDROID' \
	'-D__GNU_SOURCE=1' \
	'-DUSE_STLPORT=1' \
	'-D_STLP_USE_PTR_SPECIALIZATIONS=1' \
	'-DCHROME_BUILD_ID=""' \
	'-DNDEBUG' \
	'-DNVALGRIND' \
	'-DDYNAMIC_ANNOTATIONS_ENABLED=0'


# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES_Release := \
	$(gyp_shared_intermediate_dir) \
	$(LOCAL_PATH)/third_party/libjpeg_turbo \
	$(PWD)/frameworks/wilhelm/include \
	$(PWD)/bionic \
	$(PWD)/external/stlport/stlport


# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS_Release := \
	-fno-exceptions \
	-fno-rtti \
	-fno-threadsafe-statics \
	-fvisibility-inlines-hidden \
	-Wno-deprecated \
	-std=gnu++11 \
	-Wno-narrowing \
	-Wno-literal-suffix \
	-Wno-non-virtual-dtor \
	-Wno-sign-promo \
	-Wno-non-virtual-dtor


LOCAL_CFLAGS := $(MY_CFLAGS_$(GYP_CONFIGURATION)) $(MY_DEFS_$(GYP_CONFIGURATION))
LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES_$(GYP_CONFIGURATION))
LOCAL_CPPFLAGS := $(LOCAL_CPPFLAGS_$(GYP_CONFIGURATION))
LOCAL_ASFLAGS := $(LOCAL_CFLAGS)
### Rules for final target.

LOCAL_SHARED_LIBRARIES := \
	libstlport \
	libdl

# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: third_party_libjpeg_turbo_libjpeg_gyp

# Alias gyp target name.
.PHONY: libjpeg
libjpeg: third_party_libjpeg_turbo_libjpeg_gyp

include $(BUILD_STATIC_LIBRARY)
